/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as CustomTourRouteImport } from './routes/custom-tour'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarRentalRouteImport } from './routes/car-rental'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTourRoute = CustomTourRouteImport.update({
  id: '/custom-tour',
  path: '/custom-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRentalRoute = CarRentalRouteImport.update({
  id: '/car-rental',
  path: '/car-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/car-rental': typeof CarRentalRoute
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/car-rental': typeof CarRentalRoute
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/car-rental': typeof CarRentalRoute
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attractions'
    | '/car-rental'
    | '/contact'
    | '/custom-tour'
    | '/packages'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attractions'
    | '/car-rental'
    | '/contact'
    | '/custom-tour'
    | '/packages'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/attractions'
    | '/car-rental'
    | '/contact'
    | '/custom-tour'
    | '/packages'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttractionsRoute: typeof AttractionsRoute
  CarRentalRoute: typeof CarRentalRoute
  ContactRoute: typeof ContactRoute
  CustomTourRoute: typeof CustomTourRoute
  PackagesRoute: typeof PackagesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-tour': {
      id: '/custom-tour'
      path: '/custom-tour'
      fullPath: '/custom-tour'
      preLoaderRoute: typeof CustomTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-rental': {
      id: '/car-rental'
      path: '/car-rental'
      fullPath: '/car-rental'
      preLoaderRoute: typeof CarRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttractionsRoute: AttractionsRoute,
  CarRentalRoute: CarRentalRoute,
  ContactRoute: ContactRoute,
  CustomTourRoute: CustomTourRoute,
  PackagesRoute: PackagesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
